---
notifications:
  email:
    on_success: never
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
env:
  global:
    - REPORTER=Dot
  matrix:
    - BUNDLE="ember=1.2.2&jQuery=1.10.2"
    - BUNDLE="ember=1.2.2&jQuery=2.0.3"
    - BUNDLE="ember=1.3.2&jQuery=1.10.2"
    - BUNDLE="ember=1.3.2&jQuery=2.0.3"
    - BUNDLE="ember=1.4.0&jQuery=1.11.1"
    - BUNDLE="ember=1.4.0&jQuery=2.1.1"
    - BUNDLE="ember=1.5.1&jQuery=1.11.1"
    - BUNDLE="ember=1.5.1&jQuery=2.1.1"
    - BUNDLE="ember=1.6.1&jQuery=1.11.1"
    - BUNDLE="ember=1.6.1&jQuery=2.1.1"
    - BUNDLE="ember=1.7.0&jQuery=1.11.1"
    - BUNDLE="ember=1.7.0&jQuery=2.1.1"
