---
language: node_js
node_js:
  - "6"

sudo: false

env:
  matrix:
    - SCRIPT=test:all
    - SCRIPT=test:fastboot
    - SCRIPT=test:node

cache:
  yarn: true
  directories:
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - bower install

script:
  - npm run $SCRIPT

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: dKp+BvoSv8vUN90m9fH2oOK/sQ12K5B5BrWjfn1m2evpc9TFZGHLlqSsAw4Cq9JmK7SgRKsuh4O2k1CO8QAXW6mMjD/NSGJfBz+grdXE20kqOlIPvj9sQ9PVpqgmTA5bZvhbhXn8ybKqgTabZZrED9eMkrSqMN5xU1oW414DNwQ=
  on:
    tags: true
    repo: simplabs/ember-simple-auth

after_deploy:
  - npm i -g now-pipeline
  - now-pipeline-prune && now-pipeline --alias ember-simple-auth.now.sh
  - cd server && now-pipeline-prune && now-pipeline --alias ember-simple-auth-server.now.sh

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=

env:
  now:
    secure: CTqDGGwSMS1j96bnoCldK/QDiLaPR2xwhSjZtmSM2/jBOrkh7uTh9HIw14dIpEXg4hKVvPBrZQ2igDsT+qktXzzrai7NO2cl8C0CfLRBSSZhDGlTb0IbcoREU6UORRHX6PwfwpMpIobvh1MRDSuOYaDh1jnTI3BKqwro3uhMO7g=
